"use client";

import { useState } from "react";
import type { Diagnosis } from "@/lib/schemas";

function ReviewBox({ title, items, className }: { title: string; items: string[]; className: string }) { return <div className={`review-box ${className}`}><h3>{title}</h3>{items.length ? <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul> : <div className="empty-copy">None right now.</div>}</div>; }

export function DiagnosisStep({ diagnosis, mockMode, onReset }: { diagnosis: Diagnosis; mockMode: boolean; onReset: () => void }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { try { await navigator.clipboard.writeText(diagnosis.notePatchMarkdown); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } };
  return <section className="panel" aria-labelledby="diagnosis-title"><div className="panel-head"><div><h2 className="panel-title" id="diagnosis-title">Knowledge diagnosis</h2><p className="panel-copy">What is solid, what needs another pass, and the smallest note change justified by your answers.</p></div>{mockMode && <span className="mode-chip">Development demo</span>}</div><div className="panel-body"><div className="diagnosis-grid"><div><span className="section-label">Topic states</span><div className="concept-stack">{diagnosis.conceptStates.map((item, index) => <div className="concept-row" key={`${item.topic}-${index}`}><strong>{item.topic}</strong><span className={`state-chip state-${item.state.toLowerCase()}`}>{item.state.replaceAll("_", " ")}</span><p>{item.reason}</p></div>)}</div></div><div><span className="section-label">Minimal note patch</span><div className="patch"><div className="patch-head"><h3>Markdown additions & corrections</h3><button className="copy-button" type="button" onClick={copy} disabled={!diagnosis.notePatchMarkdown}>{copied ? "Copied" : "Copy Markdown"}</button></div><pre>{diagnosis.notePatchMarkdown || "No note patch is needed from this diagnostic."}</pre></div></div><div className="review-grid"><ReviewBox title="Review again" items={diagnosis.reviewAgain} className="review-again" /><ReviewBox title="Unstable" items={diagnosis.unstable} className="review-unstable" /><ReviewBox title="Solid" items={diagnosis.solid} className="review-solid" /></div></div><div className="actions"><button className="button button-secondary" type="button" onClick={onReset}>Start a new analysis</button></div></div></section>;
}
