"use client";

import type { Question } from "@/lib/schemas";

const confidenceLabels = ["Completely unsure", "Guessing", "Mostly sure", "Very sure"];
export type AnswerState = Record<string, { answer: string; confidence: number | null }>;

export function QuizStep({ questions, answers, setAnswers, submitting, error, onSubmit }: { questions: Question[]; answers: AnswerState; setAnswers: (answers: AnswerState) => void; submitting: boolean; error: string; onSubmit: () => void }) {
  const complete = questions.every((question) => answers[question.id]?.answer.trim() && answers[question.id]?.confidence !== null);
  const update = (id: string, patch: Partial<AnswerState[string]>) => setAnswers({ ...answers, [id]: { answer: answers[id]?.answer ?? "", confidence: answers[id]?.confidence ?? null, ...patch } });
  return <section className="panel" aria-labelledby="quiz-title"><div className="panel-head"><div><h2 className="panel-title" id="quiz-title">Diagnostic quiz</h2><p className="panel-copy">Answer from memory. The hidden rubric will assess both your response and how certain you felt.</p></div><span className="mode-chip">{questions.length} questions</span></div><div className="panel-body"><div className="quiz-stack">{questions.map((question, index) => <article className="question-card" key={question.id}><div className="question-head"><span className="question-index">Question {index + 1}</span><span className="type-chip">{question.type}</span></div><div className="question-topic">Topic · {question.topic}</div><p className="question-text">{question.question}</p>{question.code && <pre className="code"><code>{question.code}</code></pre>}<label className="section-label" htmlFor={`answer-${question.id}`}>Your answer</label><textarea className="answer" id={`answer-${question.id}`} value={answers[question.id]?.answer ?? ""} onChange={(event) => update(question.id, { answer: event.target.value })} placeholder="Explain your reasoning…" /><div className="confidence"><div className="confidence-label">Confidence</div><div className="confidence-options" role="group" aria-label={`Confidence for question ${index + 1}`}>{confidenceLabels.map((label, value) => <button type="button" key={label} className={`confidence-option ${answers[question.id]?.confidence === value ? "selected" : ""}`} onClick={() => update(question.id, { confidence: value })} aria-pressed={answers[question.id]?.confidence === value}><span>{value}</span>{label}</button>)}</div></div></article>)}</div>{error && <div className="error" role="alert">{error}</div>}<div className="actions"><button className="button button-primary" type="button" onClick={onSubmit} disabled={!complete || submitting}>{submitting ? <span className="loading"><span className="spinner" />Diagnosing…</span> : "Submit answers"}</button></div></div></section>;
}
